### ISSUE TITLE
Upstreaming tracker

### ISSUE THREAD

**Issue by wentam** [wentam/sxmo-nix#39]
## pkgs
- [ ] [autologin](https://github.com/wentam/sxmo-nix/tree/main/pkgs/autologin)
- [ ] [codemadness-frontends](https://github.com/wentam/sxmo-nix/tree/main/pkgs/codemadness-frontends)
- [ ] [mmsd-tng](https://github.com/wentam/sxmo-nix/tree/main/pkgs/mmsd-tng)
- [x] [mnc](https://github.com/wentam/sxmo-nix/tree/main/pkgs/mnc)
- [x] [proycon-wayout](https://github.com/wentam/sxmo-nix/tree/main/pkgs/proycon-wayout)
- [x] [superd](https://github.com/wentam/sxmo-nix/tree/main/pkgs/superd)
- [ ] [sxmo-dmenu](https://github.com/wentam/sxmo-nix/tree/main/pkgs/sxmo-dmenu)
- [ ] [sxmo-dwm](https://github.com/wentam/sxmo-nix/tree/main/pkgs/sxmo-dwm)
- [ ] [sxmo-st](https://github.com/wentam/sxmo-nix/tree/main/pkgs/sxmo-st)
- [ ] [sxmo-utils](https://github.com/wentam/sxmo-nix/tree/main/pkgs/sxmo-utils)
- [ ] [tinydm](https://github.com/wentam/sxmo-nix/tree/main/pkgs/tinydm)
- [ ] [vvmd](https://github.com/wentam/sxmo-nix/tree/main/pkgs/vvmd)

## modules
- [ ] [autologin](https://github.com/wentam/sxmo-nix/tree/main/modules/autologin)
- [ ] [sxmo](https://github.com/wentam/sxmo-nix/tree/main/modules/sxmo)
- [ ] [tinydm](https://github.com/wentam/sxmo-nix/tree/main/modules/tinydm)
